feign:
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000
                loggerLevel: full

weather:
    api:
        url: https://goweather.herokuapp.com/
